# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/peter/github/sfml-course

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/peter/github/sfml-course

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/github/sfml-course/CMakeFiles /home/peter/github/sfml-course/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/peter/github/sfml-course/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pacwoman

# Build rule for target.
pacwoman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pacwoman
.PHONY : pacwoman

# fast build rule for target.
pacwoman/fast:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/build
.PHONY : pacwoman/fast

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameState.o: src/GameState.cpp.o

.PHONY : src/GameState.o

# target to build an object file
src/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/GameState.cpp.o
.PHONY : src/GameState.cpp.o

src/GameState.i: src/GameState.cpp.i

.PHONY : src/GameState.i

# target to preprocess a source file
src/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/GameState.cpp.i
.PHONY : src/GameState.cpp.i

src/GameState.s: src/GameState.cpp.s

.PHONY : src/GameState.s

# target to generate assembly for a file
src/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/GameState.cpp.s
.PHONY : src/GameState.cpp.s

src/entities/Bonus.o: src/entities/Bonus.cpp.o

.PHONY : src/entities/Bonus.o

# target to build an object file
src/entities/Bonus.cpp.o:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Bonus.cpp.o
.PHONY : src/entities/Bonus.cpp.o

src/entities/Bonus.i: src/entities/Bonus.cpp.i

.PHONY : src/entities/Bonus.i

# target to preprocess a source file
src/entities/Bonus.cpp.i:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Bonus.cpp.i
.PHONY : src/entities/Bonus.cpp.i

src/entities/Bonus.s: src/entities/Bonus.cpp.s

.PHONY : src/entities/Bonus.s

# target to generate assembly for a file
src/entities/Bonus.cpp.s:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Bonus.cpp.s
.PHONY : src/entities/Bonus.cpp.s

src/entities/Character.o: src/entities/Character.cpp.o

.PHONY : src/entities/Character.o

# target to build an object file
src/entities/Character.cpp.o:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Character.cpp.o
.PHONY : src/entities/Character.cpp.o

src/entities/Character.i: src/entities/Character.cpp.i

.PHONY : src/entities/Character.i

# target to preprocess a source file
src/entities/Character.cpp.i:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Character.cpp.i
.PHONY : src/entities/Character.cpp.i

src/entities/Character.s: src/entities/Character.cpp.s

.PHONY : src/entities/Character.s

# target to generate assembly for a file
src/entities/Character.cpp.s:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Character.cpp.s
.PHONY : src/entities/Character.cpp.s

src/entities/Dot.o: src/entities/Dot.cpp.o

.PHONY : src/entities/Dot.o

# target to build an object file
src/entities/Dot.cpp.o:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Dot.cpp.o
.PHONY : src/entities/Dot.cpp.o

src/entities/Dot.i: src/entities/Dot.cpp.i

.PHONY : src/entities/Dot.i

# target to preprocess a source file
src/entities/Dot.cpp.i:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Dot.cpp.i
.PHONY : src/entities/Dot.cpp.i

src/entities/Dot.s: src/entities/Dot.cpp.s

.PHONY : src/entities/Dot.s

# target to generate assembly for a file
src/entities/Dot.cpp.s:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Dot.cpp.s
.PHONY : src/entities/Dot.cpp.s

src/entities/Ghost.o: src/entities/Ghost.cpp.o

.PHONY : src/entities/Ghost.o

# target to build an object file
src/entities/Ghost.cpp.o:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Ghost.cpp.o
.PHONY : src/entities/Ghost.cpp.o

src/entities/Ghost.i: src/entities/Ghost.cpp.i

.PHONY : src/entities/Ghost.i

# target to preprocess a source file
src/entities/Ghost.cpp.i:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Ghost.cpp.i
.PHONY : src/entities/Ghost.cpp.i

src/entities/Ghost.s: src/entities/Ghost.cpp.s

.PHONY : src/entities/Ghost.s

# target to generate assembly for a file
src/entities/Ghost.cpp.s:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Ghost.cpp.s
.PHONY : src/entities/Ghost.cpp.s

src/entities/Pacwoman.o: src/entities/Pacwoman.cpp.o

.PHONY : src/entities/Pacwoman.o

# target to build an object file
src/entities/Pacwoman.cpp.o:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Pacwoman.cpp.o
.PHONY : src/entities/Pacwoman.cpp.o

src/entities/Pacwoman.i: src/entities/Pacwoman.cpp.i

.PHONY : src/entities/Pacwoman.i

# target to preprocess a source file
src/entities/Pacwoman.cpp.i:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Pacwoman.cpp.i
.PHONY : src/entities/Pacwoman.cpp.i

src/entities/Pacwoman.s: src/entities/Pacwoman.cpp.s

.PHONY : src/entities/Pacwoman.s

# target to generate assembly for a file
src/entities/Pacwoman.cpp.s:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/entities/Pacwoman.cpp.s
.PHONY : src/entities/Pacwoman.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/pacwoman.dir/build.make CMakeFiles/pacwoman.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... pacwoman"
	@echo "... edit_cache"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameState.o"
	@echo "... src/GameState.i"
	@echo "... src/GameState.s"
	@echo "... src/entities/Bonus.o"
	@echo "... src/entities/Bonus.i"
	@echo "... src/entities/Bonus.s"
	@echo "... src/entities/Character.o"
	@echo "... src/entities/Character.i"
	@echo "... src/entities/Character.s"
	@echo "... src/entities/Dot.o"
	@echo "... src/entities/Dot.i"
	@echo "... src/entities/Dot.s"
	@echo "... src/entities/Ghost.o"
	@echo "... src/entities/Ghost.i"
	@echo "... src/entities/Ghost.s"
	@echo "... src/entities/Pacwoman.o"
	@echo "... src/entities/Pacwoman.i"
	@echo "... src/entities/Pacwoman.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

